### ISSUE TITLE
Feature Request: Passing advanced parameters

### ISSUE THREAD

**Issue by RestNPizza** [skylord123/node-red-contrib-gamedig#10]
Hello,

First off, I love this node and think it's super useful! I had one request that I was hoping you could implement. In the main version of gamedig, you can pass through advanced parameters (see note below pulled from the gamedig github). Would it be possible to add an input to the node that allowed users to add an advanced parameter? It could be a text box where the user would enter the advanced parameters that the node would automatically include in the gamedig call. For example, if I added "--debug" to this advanced parameters input, it would include that in the call and the return would be the debug formatted data.

> The output of the command will be in JSON format. Additional advanced parameters can be passed in as well: --debug, --pretty, --socketTimeout 5000, --requestRules etc.

**Comment by skylord123** [comment]
Sure! We already have some of the options available but it would be nice to cover all of them so I will look into this.

**Comment by RestNPizza** [comment]
Awesome! Thanks so much!

**Comment by RestNPizza** [comment]
> Sure! We already have some of the options available but it would be nice to cover all of them so I will look into this.

Not trying to be pushy but just wondering if whenever this is implemented, will I see that the node is available for update in node red?

**Comment by skylord123** [comment]
Yes you will see an update available when you view the module under the palette manager. I'll also post here when it's done. I've just been busy with some personal stuff right now but I will get to it and update you here when it's done.

**Comment by RestNPizza** [comment]
No worries! Just wanted to make sure how I'd see it. Thanks!

**Comment by skylord123** [comment]
@RestNPizza Just dropped release [v2.2.0](https://github.com/skylord123/node-red-contrib-gamedig/releases/tag/2.2.0), check it out and let me know if you have any issues or need anything else added.

**Comment by RestNPizza** [comment]
Thanks for implementing! I updated and tried it out and I'm not seeing any difference in the output when debug is checked... 

Debugging enabled:
![Screenshot_20230510_223549_VNC Viewer.jpg](https://github.com/skylord123/node-red-contrib-gamedig/assets/8268870/e6716d0e-49d5-4de8-9ac8-e3b87669726e)

Debugging disabled:
![Screenshot_20230510_223815_VNC Viewer.jpg](https://github.com/skylord123/node-red-contrib-gamedig/assets/8268870/22296464-f474-4da8-b760-48ea5c6a559d)

**Comment by skylord123** [comment]
No problem! 

Debugging enabled outputs to stdout. If you are running in docker you can see this by viewing the container logs. Otherwise you will have to find the log file. It outputs a lot of stuff so I recommend only using it to debug query issues.

**Comment by RestNPizza** [comment]
Gotcha. Thanks so much!
