### ISSUE TITLE
Player keyhash issue for BF1942 (Fixed in latest version of gamedig)

### ISSUE THREAD

**Issue by RestNPizza** [skylord123/node-red-contrib-gamedig#13]
A few months ago, I reported to the game-dig team a bug related to BF1942 queries. The issue is that game-dig returns an incomplete keyhash for Battlefield 1942 when the keyhash starts with an integer. They've released a fix for this last week and I just tested via command prompt and can confirm it has been fixed. Would you be able to update this node with the most recent version of game-dig to incorporate the fix? It would be much appreciated.

Thanks! :)

**Comment by skylord123** [comment]
Sure thing, I'll post here once I get it updated. Adding to my todo list.

Thanks!

**Comment by RestNPizza** [comment]
> Sure thing, I'll post here once I get it updated. Adding to my todo list.
> 
> Thanks!

Thanks so much!!!

**Comment by skylord123** [comment]
@RestNPizza just pushed out a new release with the latest gamedig version. Test that out and let me know how it goes.

Thanks

**Comment by RestNPizza** [comment]
That did the trick! Thanks so much!!!!

**Comment by skylord123** [comment]
Awesome, glad it's working for you now.
