### ISSUE TITLE
Issues using node after 3.0.0 update

### ISSUE THREAD

**Issue by RestNPizza** [skylord123/node-red-contrib-gamedig#15]
Hello,
I recently updated this node in my node-red instance to v3.0.0 and ever since, i've been having issues using it. Initially, I received the following error:
`Error: Invalid game: bf1942`

So I went here to the [Gamedig Games List](https://github.com/gamedig/node-gamedig/blob/master/GAMES_LIST.md) and noticed that at some point, Battlefield 1942 changed from the gametype of 'bf1942' to 'battlefield1942'. I updated the gametype in the node and am now getting the following error, no matter what host I query:
`Error: Failed all 2 attempts`

I've tried dozens of host ips that I know without a doubt are online, all with the same result. I've been using this node for over a year without issue so I am guessing it has something to do with the 3.0.0 update. I also tried a teamspeak 3 server that I know is online and got the same result so the issue doesn't appear to be tied to the new game type.

Here's how I have the node set up if you'd like to try to replicate:
Name: HKHP 24/7 ElAlamein Modded
Server Type: battlefield1942
Host: 198.27.66.173
Port: 23000
Strip Colors: true
IP Rules: IPv4 and IPv6
(All other node options are empty or unchecked)

**Comment by RestNPizza** [comment]
Here's debug info in case you need it:

Q#642128 UDP timeout detected
Q#642128 Query failed with error Error: UDP - Timed out after 2000ms
    at Timeout.<anonymous> (/data/node_modules/gamedig/dist/index.cjs:11962:18)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7)
Q#642129 Starting
Q#642129 Protocol: gamespy1
Q#642129 Options: {
  socketTimeout: 2000,
  attemptTimeout: 10000,
  maxRetries: 1,
  stripColors: true,
  portCache: true,
  noBreadthOrder: false,
  ipFamily: 0,
  requestPlayers: true,
  port: 23000,
  protocol: 'gamespy1',
  type: 'battlefield1942',
  host: '198.27.66.173',
  address: undefined,
  maxAttempts: 1,
  givenPortOnly: false,
  debug: true,
  requestRules: undefined,
  strip_colors: true
}
undefined:23000 UDP(33761)-->
Buffer length: 20 bytes
5c 73 74 61 74 75 73 5c 78 73 65 72 76 65 72 71 75 65 72 79 
\  s  t  a  t  u  s  \  x  s  e  r  v  e  r  q  u  e  r  y

**Comment by skylord123** [comment]
Maybe you passed the IP address to the host input instead of the address input?

I am querying the server fine with this flow:
```
[
    {
        "id": "f9fded283f17f573",
        "type": "query-game-server",
        "z": "d7c6f8639e739cc4",
        "name": "",
        "server_type": "battlefield1942",
        "host": "",
        "address": "198.27.66.173",
        "port": "",
        "halt_if": "",
        "max_attempts": "",
        "socket_timeout": "",
        "attempt_timeout": "",
        "given_port_only": "",
        "ip_family": "0",
        "debug": "",
        "strip_colors": true,
        "request_rules": "",
        "output_options": "",
        "x": 510,
        "y": 720,
        "wires": [
            [
                "8b9ba53192597b43"
            ]
        ]
    },
    {
        "id": "d17cc66ee00edcb5",
        "type": "inject",
        "z": "d7c6f8639e739cc4",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 280,
        "y": 720,
        "wires": [
            [
                "f9fded283f17f573"
            ]
        ]
    },
    {
        "id": "8b9ba53192597b43",
        "type": "debug",
        "z": "d7c6f8639e739cc4",
        "name": "debug 191",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 770,
        "y": 720,
        "wires": []
    }
]
```

**Comment by RestNPizza** [comment]
Yup. That's it! I just had to update my existing nodes to use address instead of host. Thanks for your help!!

**Comment by skylord123** [comment]
Awesome, glad it's working.
